#ifndef __SYSCALLDEF_H__
#define __SYSCALLDEF_H__

#define TRAITANT_START 1
#define TRAITANT_CURRENTCLOCK 2
#define TRAITANT_EXIT 3
#define TRAITANT_GETPID 4
#define TRAITANT_GETPRIO 5
#define TRAITANT_CHPRIO 6
#define TRAITANT_CONS_WRITE 7
#define TRAITANT_CONS_ECHO 8
#define TRAITANT_CONS_READ 9
#define TRAITANT_KILL 10
#define TRAITANT_PCREATE 11
#define TRAITANT_PSEND 12
#define TRAITANT_PCOUNT 13
#define TRAITANT_PDELETE 14
#define TRAITANT_PRECEIVE 15
#define TRAITANT_PRESET 16
#define TRAITANT_WAIT_CLOCK 17
#define TRAITANT_CLOCK_SETTINGS 18
#define TRAITANT_WAITPID 19
#define TRAITANT_CONSOLE_PUTBYTES 20

#endif